#pragma once
#include "wt_mip.h"

namespace mt {

// Built-in wavetables: generated by wtBuild from these spectra, cached in the bank as "*NAME".
constexpr int kWtBuiltins = 8;
const char* wtBuiltinName(int i);     // "*SAWSQR", ...; nullptr out of range
int wtBuiltinFind(const char* name);  // ignoring case, -1
inline bool isWtBuiltin(const char* n) { return n && n[0] == '*'; }
// Source of built-in i for wtBuild. Not reentrant: *SYNC / *BELL use a shared static buffer.
struct WtBuiltinSrc final : WtSpectrumSource {
  int id;
  explicit WtBuiltinSrc(int i) : id(i) {}
  void spectrum(int f, float* re, float* im) override;
};

}  // namespace mt
