#!/usr/bin/env python3
"""Access Virus arp patterns of docs/AudioXL Arpeggiator.amxd as D-TRK factory arp text.

python3 -I tools/virus_arp.py "docs/AudioXL Arpeggiator.amxd" lib/core/src/arp_virus.inc

The device's v8 script ends with PATTERNS = [{"l": 1536, "e": [[onset, gate, vel%], ...]}, ...]
at 192 PPQ, 16 cells of 96 ticks. One D-TRK step = 48 ticks (32 steps). An off-grid event goes to
the nearest step with the rest as nudge (% of a step); two events in one step: the louder stays.
"""
import json
import sys

GRID = 48
STEPS = 32


def load(path):
    data = open(path, 'rb').read()
    patch = json.loads(data[data.index(b'{'):data.rindex(b'}') + 1])
    for b in patch['patcher']['boxes']:
        tf = b['box'].get('textfile')
        text = tf.get('text', '') if isinstance(tf, dict) else ''
        if 'PATTERNS = [' in text:
            i = text.rindex('PATTERNS = [') + len('PATTERNS = ')  # the last one: the generated data
            return json.loads(text[i:text.index('];', i) + 1])
    sys.exit('no PATTERNS in ' + path)


def token(vel, gate, nudge):
    c = 'X' if vel >= 115 else ('o' if vel < 75 else 'x')
    return '%s:%d:%d' % (c, vel, gate) + (':%d' % nudge if nudge else '')


def convert(p):
    assert p['l'] == GRID * STEPS, p['l']
    steps = [None] * STEPS
    for onset, gate, vel in p['e']:
        s = (onset + GRID // 2) // GRID
        nudge = round((onset - s * GRID) * 100 / GRID)
        s %= STEPS
        vel = min(vel, 200)
        if steps[s] is None or vel > steps[s][0]:
            steps[s] = (vel, max(1, round(gate * 100 / GRID)), nudge)
    return ' '.join('.' if x is None else token(*x) for x in steps)


def main():
    pats = load(sys.argv[1])
    assert len(pats) == 64, len(pats)
    with open(sys.argv[2], 'w') as f:
        f.write('// Generated by tools/virus_arp.py from docs/AudioXL Arpeggiator.amxd\n')
        f.write('// (Access Virus B/Indigo OS 4.90). Do not edit.\n')
        for i, p in enumerate(pats, 1):
            f.write('    {"VIRUS %02d", "%s"},\n' % (i, convert(p)))


main()
